#!/usr/bin/env bash

#PBS -l nodes=1:ppn=1
#PBS -l walltime=30:00:00
#PBS -l pmem=720gb
#PBS -l partition = bigmem
#PBS -A <account>


cd ~
cd /staging/leuven/stg_00092/IBP_PRSproject/1_Intestinal_Bowel_Disease/PRS_pipeline_binary_phenotypes/scripts/

module purge
eval "$(conda shell.bash hook)"
conda activate $VSC_DATA/miniconda3/envs/snakemake_PRS

snakemake -s LD_pred_all_snakefile --cores 4 --use-conda
